private _text = "{{Feature|important|The content of this page was generated by script. Manual edits might get lost.}}" + endl;
_text = _text + "{| class=""wikitable sortable"""  + endl + "|-" + endl;
_text = _text + "! TAG !! Category !! Functions"  + endl + "|-" + endl;

private _indexConfig = _forEachIndex;
{
	// Tags
	private _nameTAG = configName _x;
	private _valueTAG = getText (_x >> "tag");

	if (_valueTAG == "") then { _valueTag = configName _x };
	{
		// Categories
		private _nameCategory = configName _x;
		_text = _text + endl + "|-" + endl + "!" + _nameTAG + endl + "!" + _nameCategory + endl + "|";

		private _functions = [];

		{ // Functions
			_functions pushBack (toUpper _valueTAG + "_fnc_" + (configName _x));
		} forEach ((configFile >> "CfgFunctions" >> _nameTAG >> _nameCategory) call BIS_fnc_returnChildren);

		_text = _text + "|" + endl;

		private _collapse = count _functions > 10;
    if (_collapse) then
    {
      _text = _text + "{| class=""wikitable mw-collapsible mw-collapsed""" + endl;
      _text = _text + "! Functions" + endl;
      _text = _text + "|-" + endl;
      _text = _text + "|" + endl;
    };

		{
			_text = _text + "* " + _x + endl;
		} forEach _functions;

    if (_collapse) then
    {
      _text = _text + "|}" + endl;
    };
	} forEach ("true" configClasses _x);
} forEach ("configSourceMod _x == ""SPE""" configClasses (configFile >> "CfgFunctions"));

_text = _text + "|}";

copyToClipboard _text;