name = "VANA - Loadout Management";
author = "Eathox, modified by R3vo"
tooltip = "$STR_VANA_TITLE";
tooltipOwned = "$STR_VANA_TITLE";
overviewText = "$STR_VANA_TITLE";
overview = "$STR_VANA_Overview";
actionName = "$STR_VANA_ActionName";
picture = "v\vana\addons\loadoutmanagement\data\picture_ca.paa";
logoSmall = "v\vana\addons\loadoutmanagement\data\logoSmall_ca.paa";
logo = "v\vana\addons\loadoutmanagement\data\logoSmall_ca.paa";
logoOver = "v\vana\addons\loadoutmanagement\data\logoSmall_ca.paa";
action = "https://github.com/R3voA3/VANA";