class CfgFunctions
{
  #include "TPD\CfgFunctions.hpp"
  class R3vo
  {
    class ScriptLibrary
    {
      class acceleration;
      class alarm;
      class artilleryFire;
      class assignNVGs;
      class bitFlagToKey;
      class calculateCenter;
      class carShow;
      class closeTerminal;
      class countdown;
      class createComposition;
      class createMarkerGUI;
      class createObjectLine;
      class createWeaponWall;
      class destroyLights;
      class diagActiveScripts;
      class exportCfgFunction;
      class exportCommandsForSyntaxHighlighter;
      class exportConfigValue;
      class exportFunctionNamesToClipboard;
      class exportFunctionsToWiki;
      class exportMarkerColours;
      class exportRespawnInventory;
      class exportUnitInsignias;
      class fireAtTarget;
      class garbageCollector;
      class getProfileColor;
      class initRevive;
      class knowsAbout;
      class layerManager;
      class logA3Modules;
      class markerIcon;
      class measureDistance;
      class perimeter;
      class popUpTargets;
      class removeNVG;
      class restrictWeapons;
      class revealUnits;
      class scanHorizonAATurret;
      class setSkill;
      class showFps;
      class simpleConv;
      class strategicMap;
      class uav;
      class unstuckGroup;
      class vehicleService;
      class verticalModeMessage;
    };
  };
};